# This file was generated by GoReleaser. DO NOT EDIT.
class BuffaloHeroku < Formula
  desc ""
  homepage ""
  version "1.0.9"

  if OS.mac?
    url "https://github.com/gobuffalo/buffalo-heroku/releases/download/v1.0.9/buffalo-heroku_1.0.9_darwin_amd64.tar.gz"
    sha256 "a1b9ce9df3e5f923312b9dbe0689338d9eff5db092e15ca20ff1465855956f3e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/buffalo-heroku/releases/download/v1.0.9/buffalo-heroku_1.0.9_linux_amd64.tar.gz"
      sha256 "f06d10c9032c90a3ea27f736dea0cd2e2494d66dfd46ae11a9993ed1d7952c9e"
    end
  end

  def install
    bin.install "buffalo-heroku"
  end
end
