# This file was generated by GoReleaser. DO NOT EDIT.
class BuffaloPop < Formula
  desc "Buffalo plugin to work with gobuffalo/pop"
  homepage ""
  version "2.3.0"

  if OS.mac?
    url "https://github.com/gobuffalo/buffalo-pop/releases/download/v2.3.0/buffalo-pop_2.3.0_darwin_amd64.tar.gz"
    sha256 "c82801dbebe395e79067630c9ee6554481af451483a791408023580801095f9e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/buffalo-pop/releases/download/v2.3.0/buffalo-pop_2.3.0_linux_amd64.tar.gz"
      sha256 "19c795c78f6ddf42084ab8dfd9dd477c8cb9365c18b6a33db63085f73eb2d394"
    end
  end

  def install
    bin.install "buffalo-pop"
  end
end
