# This file was generated by GoReleaser. DO NOT EDIT.
class BuffaloGoth < Formula
  desc ""
  homepage ""
  version "1.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gobuffalo/buffalo-goth/releases/download/v1.1.1/buffalo-goth_1.1.1_Darwin_x86_64.tar.gz"
    sha256 "eefa0f5385b308254c7d5388c8ef53cd70164ceed02601828703ebde0ba54c66"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/buffalo-goth/releases/download/v1.1.1/buffalo-goth_1.1.1_Linux_x86_64.tar.gz"
      sha256 "75bb094269770f8e7dd078f0d57d3b95a62f01bd06507f597eeb0a4a91e68c26"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gobuffalo/buffalo-goth/releases/download/v1.1.1/buffalo-goth_1.1.1_Linux_arm64.tar.gz"
        sha256 "81919131dcf2a9223f8d5b75d220d6e2494c3a55f37c6e1b50f95a75c7a4400f"
      else
        url "https://github.com/gobuffalo/buffalo-goth/releases/download/v1.1.1/buffalo-goth_1.1.1_Linux_armv6.tar.gz"
        sha256 "9147c5c99f54ab5e7777fd82a1433c337c5ed352e7d377cd21059cf36bed9dec"
      end
    end
  end

  def install
    bin.install "buffalo-goth"
  end
end
