# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Buffalo < Formula
  desc ""
  homepage ""
  version "0.17.0-alpha.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/cli/releases/download/v0.17.0-alpha.3/cli_0.17.0-alpha.3_Darwin_x86_64.tar.gz"
      sha256 "ebacd06c1868ca55437c8e15c9c8e4b2ba36291d5a99ab780baaea02fff111e9"
    end
    if Hardware::CPU.arm?
      url "https://github.com/gobuffalo/cli/releases/download/v0.17.0-alpha.3/cli_0.17.0-alpha.3_Darwin_arm64.tar.gz"
      sha256 "91dd1b40167b8e9891ea2a164d5a0f014aef4ea087c21ac1af8b8e251eca652e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/cli/releases/download/v0.17.0-alpha.3/cli_0.17.0-alpha.3_Linux_x86_64.tar.gz"
      sha256 "c8b1b624f2f05e1cab9449a6f6d602d8913f21a621f56a960609095e4718a7c0"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gobuffalo/cli/releases/download/v0.17.0-alpha.3/cli_0.17.0-alpha.3_Linux_armv6.tar.gz"
      sha256 "c0246e8df8a4f7fa8ef555b9037f03dd50891e4d5a88097339ec26bb163edc46"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobuffalo/cli/releases/download/v0.17.0-alpha.3/cli_0.17.0-alpha.3_Linux_arm64.tar.gz"
      sha256 "5231d71794f251de743372e0787fa7eef90f8693914d36b4aae344a204c933c5"
    end
  end

  def install
    bin.install "buffalo"
  end
end
