# This file was generated by GoReleaser. DO NOT EDIT.
class BuffaloHeroku < Formula
  desc ""
  homepage ""
  version "1.0.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gobuffalo/buffalo-heroku/releases/download/v1.0.8/buffalo-heroku_1.0.8_darwin_amd64.tar.gz"
    sha256 "42549c0e2f295e33552d99976354998505b97d683b3282042ad43e6fbb3d2bf7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/buffalo-heroku/releases/download/v1.0.8/buffalo-heroku_1.0.8_linux_amd64.tar.gz"
      sha256 "8880dc6328384fda64cb4816c79e63b32b9e29ace1c6fce519ae9b780a3dd907"
    end
  end

  def install
    bin.install "buffalo-heroku"
  end
end
