# This file was generated by GoReleaser. DO NOT EDIT.
class BuffaloCli < Formula
  desc ""
  homepage ""
  version "2.0.0-alpha.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gobuffalo/buffalo-cli/releases/download/v2.0.0-alpha.9/buffalo-cli_2.0.0-alpha.9_Darwin_x86_64.tar.gz"
    sha256 "c717bbf011129a51e144ccccf104ac561d69dfa85a26a829aca62309b9abcdf2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/buffalo-cli/releases/download/v2.0.0-alpha.9/buffalo-cli_2.0.0-alpha.9_Linux_x86_64.tar.gz"
      sha256 "5a83de277b43c883e5c395f1a1f41a991324ded43f75589ad511261810ec5917"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gobuffalo/buffalo-cli/releases/download/v2.0.0-alpha.9/buffalo-cli_2.0.0-alpha.9_Linux_arm64.tar.gz"
        sha256 "2a686736890facfda8ebd9f5acbd71539ea1b84755aef27e9f1523dc5ff84dcf"
      else
        url "https://github.com/gobuffalo/buffalo-cli/releases/download/v2.0.0-alpha.9/buffalo-cli_2.0.0-alpha.9_Linux_armv6.tar.gz"
        sha256 "f6cc46a4ff8c67b95a89e65b734a8aeb051c12a1c6ce8e0220ccaf6b9463cc04"
      end
    end
  end

  def install
    bin.install "buffalo-cli"
  end
end
