# This file was generated by GoReleaser. DO NOT EDIT.
class BuffaloDocker < Formula
  desc ""
  homepage ""
  version "1.1.2"

  if OS.mac?
    url "https://github.com/gobuffalo/buffalo-docker/releases/download/v1.1.2/buffalo-docker_1.1.2_darwin_amd64.tar.gz"
    sha256 "e81e3144660a537e61c61e650e82c96c7bd2e511e6a70cb006e1c72046d7053d"
  elsif OS.linux?
    url "https://github.com/gobuffalo/buffalo-docker/releases/download/v1.1.2/buffalo-docker_1.1.2_linux_amd64.tar.gz"
    sha256 "5af60eb839ef1885f15e283f2a708a4b27e8614f464d38cc6e5d242f391da51e"
  end

  def install
    bin.install "buffalo-docker"
  end
end
