# This file was generated by GoReleaser. DO NOT EDIT.
class BuffaloPop < Formula
  desc ""
  homepage ""
  url "https://github.com/gobuffalo/buffalo-pop/releases/download/v1.8.0/buffalo-pop_1.8.0_darwin_amd64.tar.gz"
  version "1.8.0"
  sha256 "bbea2f3f7c91db6ae073fe55ddf6e5b14339dda0f1b3ae61866b329f364156de"

  def install
    bin.install "buffalo-pop"
  end
end
