# This file was generated by GoReleaser. DO NOT EDIT.
class BuffaloAuth < Formula
  desc ""
  homepage ""
  version "1.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gobuffalo/buffalo-auth/releases/download/v1.2.0/buffalo-auth_1.2.0_Darwin_x86_64.tar.gz"
    sha256 "e6700341c96cda00927311dd34244386575fafef506c7645bd3d4b59bf4c386c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/buffalo-auth/releases/download/v1.2.0/buffalo-auth_1.2.0_Linux_x86_64.tar.gz"
      sha256 "8eca775c93e2c91847d28da05e0f73fbf154e9c506c599d89ff1783f19d91358"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gobuffalo/buffalo-auth/releases/download/v1.2.0/buffalo-auth_1.2.0_Linux_arm64.tar.gz"
        sha256 "01472ff8112da3874c339680107b20656fe56feb08cb5683baa6529c6605a4e8"
      else
        url "https://github.com/gobuffalo/buffalo-auth/releases/download/v1.2.0/buffalo-auth_1.2.0_Linux_armv6.tar.gz"
        sha256 "c8aaa089453cb5a8bd166cd19e8acc6d2ee0cddd93750468f68a9bfd14634108"
      end
    end
  end

  def install
    bin.install "buffalo-auth"
  end
end
