# This file was generated by GoReleaser. DO NOT EDIT.
class BuffaloCli < Formula
  desc ""
  homepage ""
  version "2.0.0-alpha.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gobuffalo/buffalo-cli/releases/download/v2.0.0-alpha.1/buffalo-cli_2.0.0-alpha.1_Darwin_x86_64.tar.gz"
    sha256 "2025254e44f9bab1b4d58ffb24b1cc4a6e553ffffa46896250af9c6188ebc6eb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/buffalo-cli/releases/download/v2.0.0-alpha.1/buffalo-cli_2.0.0-alpha.1_Linux_x86_64.tar.gz"
      sha256 "cbb5d50948cf2ce3cd22039042811e4c361ea2d1c55accc35aeab08ea7bf1914"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gobuffalo/buffalo-cli/releases/download/v2.0.0-alpha.1/buffalo-cli_2.0.0-alpha.1_Linux_arm64.tar.gz"
        sha256 "7f32a065fa6a3c182f4f165dc55f0c4d15fc487f525b93c18e7668368ba18791"
      else
        url "https://github.com/gobuffalo/buffalo-cli/releases/download/v2.0.0-alpha.1/buffalo-cli_2.0.0-alpha.1_Linux_armv6.tar.gz"
        sha256 "598cc7ede1bfe02cdb6aefe28ca8165a163e12625a78ff64fe0e6ee3d6af0a44"
      end
    end
  end

  def install
    bin.install "buffalo-cli"
  end
end
