# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clara < Formula
  desc ""
  homepage ""
  version "2.0.4-beta.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/clara/releases/download/v2.0.4-beta.2/clara_2.0.4-beta.2_Darwin_x86_64.tar.gz"
      sha256 "56633106cb812919bcc7d80d008d948e166efde162d8f8d22cf77d91d2acc1b6"

      def install
        bin.install "clara"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gobuffalo/clara/releases/download/v2.0.4-beta.2/clara_2.0.4-beta.2_Darwin_arm64.tar.gz"
      sha256 "74577bb83a058760f1e6f33bf886474b74292c1c6f5c3321c8b2b8e6f0603440"

      def install
        bin.install "clara"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gobuffalo/clara/releases/download/v2.0.4-beta.2/clara_2.0.4-beta.2_Linux_armv6.tar.gz"
      sha256 "30a14e0a4315bf8ea0847bf9860c04451a9301182cccd0bd592b7a77d89c126d"

      def install
        bin.install "clara"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/clara/releases/download/v2.0.4-beta.2/clara_2.0.4-beta.2_Linux_x86_64.tar.gz"
      sha256 "dbbc897f74afeca4908c81d4de3a0abc2b884fc8d2f858a227cacdd2b582acea"

      def install
        bin.install "clara"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobuffalo/clara/releases/download/v2.0.4-beta.2/clara_2.0.4-beta.2_Linux_arm64.tar.gz"
      sha256 "f07cae6b2d43dc24bd889c8916a7b4805970e67bf59827bc20bafba49522c89c"

      def install
        bin.install "clara"
      end
    end
  end
end
