# This file was generated by GoReleaser. DO NOT EDIT.
class Clara < Formula
  desc ""
  homepage ""
  version "2.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gobuffalo/clara/releases/download/v2.0.1/clara_2.0.1_Darwin_x86_64.tar.gz"
    sha256 "b84ac471ee1585ed88fcb1e1a63783a14393fb3152efd2bb844adc18b7b05df5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/clara/releases/download/v2.0.1/clara_2.0.1_Linux_x86_64.tar.gz"
      sha256 "5eacf051acd3859f95411fb12a27a272a694ed2aa69363e37f3b24ff5a807748"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gobuffalo/clara/releases/download/v2.0.1/clara_2.0.1_Linux_arm64.tar.gz"
        sha256 "60066ce3170d511a78a9164f3f4cc5014755b8486b6e1b6da05da4fa4b661acc"
      else
        url "https://github.com/gobuffalo/clara/releases/download/v2.0.1/clara_2.0.1_Linux_armv6.tar.gz"
        sha256 "de6e87ca42e9e0b7716a0b376b9da4eb41e7e4275756594ee6a5aae2b7a76071"
      end
    end
  end

  def install
    bin.install "clara"
  end
end
