# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clara < Formula
  desc ""
  homepage ""
  version "2.0.9"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gobuffalo/clara/releases/download/v2.0.9/clara_2.0.9_Darwin_arm64.tar.gz"
      sha256 "642992c6254369ab57a390afe49e46cb1fd2e4540e3f3f07de13ebff1e886cb8"

      def install
        bin.install "clara"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/clara/releases/download/v2.0.9/clara_2.0.9_Darwin_x86_64.tar.gz"
      sha256 "6ba39317d3449735d487c9a514cb5b0c0b89006d2cd469bb7d6b9d202814570e"

      def install
        bin.install "clara"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobuffalo/clara/releases/download/v2.0.9/clara_2.0.9_Linux_arm64.tar.gz"
      sha256 "d93e811a612d9cef9f918a2c8f3f2182b45822a6a06e95983a7fb3ab00a116fa"

      def install
        bin.install "clara"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/clara/releases/download/v2.0.9/clara_2.0.9_Linux_x86_64.tar.gz"
      sha256 "059ba18a685ddeb8ea19f3c04061b3284b159d33ca3a890f85161e4295cdc6ad"

      def install
        bin.install "clara"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gobuffalo/clara/releases/download/v2.0.9/clara_2.0.9_Linux_armv6.tar.gz"
      sha256 "82cdd42093b03a1b181ec125532040dd36c298ed7dc1d5fbf377a598652ef33f"

      def install
        bin.install "clara"
      end
    end
  end
end
