# This file was generated by GoReleaser. DO NOT EDIT.
class Genny < Formula
  desc ""
  homepage ""
  version "0.6.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gobuffalo/genny/releases/download/v0.6.0/genny_0.6.0_Darwin_x86_64.tar.gz"
    sha256 "4822b9e969c95dcda4a0930803ac611a04e27affc653249abc51206948f2d32b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/genny/releases/download/v0.6.0/genny_0.6.0_Linux_x86_64.tar.gz"
      sha256 "63b0f0b6770b2aaa126e79f2c3df546b78dc21f5ff919abfc3ee27b9cae4c489"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gobuffalo/genny/releases/download/v0.6.0/genny_0.6.0_Linux_arm64.tar.gz"
        sha256 "754f5e3f0d04d341fa84104d661f85c0428149b0791498f3d1abecbb9be18aef"
      else
        url "https://github.com/gobuffalo/genny/releases/download/v0.6.0/genny_0.6.0_Linux_armv6.tar.gz"
        sha256 "2572d5880e792a5f2876f1b56c8f28031cd56ea5e41594919144de0c3f5c0b85"
      end
    end
  end

  def install
    bin.install "genny"
  end
end
