# This file was generated by GoReleaser. DO NOT EDIT.
class Genny < Formula
  desc ""
  homepage ""
  version "0.4.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gobuffalo/genny/releases/download/v0.4.1/genny_0.4.1_darwin_amd64.tar.gz"
    sha256 "cf2fd8137426e7108f4ed0ede0f87f5321d3a0338e6766ac53cc3fcb4fd039cf"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/genny/releases/download/v0.4.1/genny_0.4.1_linux_amd64.tar.gz"
      sha256 "a203598cdfbbb42cfa521f2d84d5e6d53674da4d8108434d61fd4365e96bdd11"
    end
  end

  def install
    bin.install "genny"
  end
end
