# This file was generated by GoReleaser. DO NOT EDIT.
class Genny < Formula
  desc ""
  homepage ""
  version "0.5.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gobuffalo/genny/releases/download/v0.5.1/genny_0.5.1_Darwin_x86_64.tar.gz"
    sha256 "67c0144cfaced7b24ea40cb984446a8a7eb6cbd667ea5c69f5ebd492f7972f01"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/genny/releases/download/v0.5.1/genny_0.5.1_Linux_x86_64.tar.gz"
      sha256 "93189967608fb74231ed6ce84d7e68e86c6d0a734367fa646690c1ae579db421"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gobuffalo/genny/releases/download/v0.5.1/genny_0.5.1_Linux_arm64.tar.gz"
        sha256 "58f5393a0dbea2cdf3ae954452e6c28f4c72da8a6287b666e260fa13ca55d703"
      else
        url "https://github.com/gobuffalo/genny/releases/download/v0.5.1/genny_0.5.1_Linux_armv6.tar.gz"
        sha256 "5e9a229274199844f645526310fcdb352c1ff0f0518247d1590ae97061004004"
      end
    end
  end

  def install
    bin.install "genny"
  end
end
