# This file was generated by GoReleaser. DO NOT EDIT.
class Here < Formula
  desc ""
  homepage ""
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gobuffalo/here/releases/download/v0.4.0/here_0.4.0_darwin_amd64.tar.gz"
    sha256 "56ebdde78a978cc941bd515a2501a30037034a2373fa46912c3c50edf674ed2a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/here/releases/download/v0.4.0/here_0.4.0_linux_amd64.tar.gz"
      sha256 "f8048bfbd8a560a4927dac424e61a1a977568d58ecf6f5522d54b53746cba14f"
    end
  end

  def install
    bin.install "here"
  end
end
