# This file was generated by GoReleaser. DO NOT EDIT.
class Licenser < Formula
  desc ""
  homepage ""
  version "1.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gobuffalo/licenser/releases/download/v1.4.0/licenser_1.4.0_darwin_amd64.tar.gz"
    sha256 "e62171a96a6c4634a65da0f558b4a36711981aef6097851d0b19c2e0f311e1f3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/licenser/releases/download/v1.4.0/licenser_1.4.0_linux_amd64.tar.gz"
      sha256 "3a0400bc0cee83efcaa2f639f437a5bb679ebcaba76d0d33d3b89468df6718d9"
    end
  end

  def install
    bin.install "licenser"
  end
end
