# This file was generated by GoReleaser. DO NOT EDIT.
class Licenser < Formula
  desc ""
  homepage ""
  version "1.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gobuffalo/licenser/releases/download/v1.3.0/licenser_1.3.0_darwin_amd64.tar.gz"
    sha256 "13961d9bc296b951e3c516b4396ae2aee0beb894e08c5750362039a9d3edb702"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/licenser/releases/download/v1.3.0/licenser_1.3.0_linux_amd64.tar.gz"
      sha256 "faf280d5189c344ae2b008b60d075ef70b1062d54a979fe7b34df9cd51197b41"
    end
  end

  def install
    bin.install "licenser"
  end
end
