# This file was generated by GoReleaser. DO NOT EDIT.
class Meta < Formula
  desc ""
  homepage ""
  version "2.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gobuffalo/meta/releases/download/v2.0.0/meta_2.0.0_Darwin_x86_64.tar.gz"
    sha256 "4b8534c9bb374645a07545ff611809255faa3c991c63d24b93f5493b1539b7f8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/meta/releases/download/v2.0.0/meta_2.0.0_Linux_x86_64.tar.gz"
      sha256 "fa029971ab3a371244ec48752667f51c6b8f3e778267c1fc139c4fcd19c1f75a"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gobuffalo/meta/releases/download/v2.0.0/meta_2.0.0_Linux_arm64.tar.gz"
        sha256 "77a6f2203480c66e0c99cc552f91958ff72308d4ffbc4dd594602e7ebb450d02"
      else
        url "https://github.com/gobuffalo/meta/releases/download/v2.0.0/meta_2.0.0_Linux_armv6.tar.gz"
        sha256 "c853fb11da070109d58a66c3f0d3d55d6f2c64cd4b9429de3761c2c6ff996d5d"
      end
    end
  end

  def install
    bin.install "meta"
  end
end
