# This file was generated by GoReleaser. DO NOT EDIT.
class Packr < Formula
  desc ""
  homepage ""
  version "2.5.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gobuffalo/packr/releases/download/v2.5.3/packr_2.5.3_darwin_amd64.tar.gz"
    sha256 "0795e4b3b97eab526ba2313fe96e94dda1883529adc35736b975b39f52602363"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/packr/releases/download/v2.5.3/packr_2.5.3_linux_amd64.tar.gz"
      sha256 "558ed39913241d277b031d968cf473e42e3982e36859ab1fb073f49d246246e8"
    end
  end

  def install
    bin.install "packr"
  end
end
