# This file was generated by GoReleaser. DO NOT EDIT.
class Plush < Formula
  desc ""
  homepage ""
  url "https://github.com/gobuffalo/plush/releases/download/v3.8.1/plush_3.8.1_darwin_amd64.tar.gz"
  version "3.8.1"
  sha256 "9a2ad90f17cabf34ed2b6c1ef27f7f899e8837de825c664c8fcef5b10b0c98f3"

  def install
    bin.install "plush"
  end
end
