# This file was generated by GoReleaser. DO NOT EDIT.
class Plush < Formula
  desc ""
  homepage ""
  version "3.8.3"

  if OS.mac?
    url "https://github.com/gobuffalo/plush/releases/download/v3.8.3/plush_3.8.3_darwin_amd64.tar.gz"
    sha256 "644f10b4ec4f5fd81f287ac4b760db9c1415806f6d2bf0f2ecfd8f76856fa227"
  elsif OS.linux?
    url "https://github.com/gobuffalo/plush/releases/download/v3.8.3/plush_3.8.3_linux_amd64.tar.gz"
    sha256 "215132cc3165642a3732043d7bee8c6ba17b6930358a4e6c7b3ee17d0b263ee7"
  end

  def install
    bin.install "plush"
  end
end
