# This file was generated by GoReleaser. DO NOT EDIT.
class Pop < Formula
  desc "A Tasty Treat For All Your Database Needs"
  homepage "https://gobuffalo.io/docs/db/getting-started"
  version "5.0.11"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gobuffalo/pop/releases/download/v5.0.11/pop_5.0.11_darwin_amd64.tar.gz"
    sha256 "7051bf7c0b274bc93be958b61ad24affb455186f1b31f0b800f7145643c57f03"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/pop/releases/download/v5.0.11/pop_5.0.11_linux_amd64.tar.gz"
      sha256 "7f447c2f136ca611717ac635cc4112d12e0d5764e4ba7b5502a364dcb76080a4"
    end
  end

  def install
    bin.install "soda"
  end
end
