# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Refresh < Formula
  desc ""
  homepage ""
  version "1.13.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/refresh/releases/download/v1.13.3/refresh_1.13.3_Darwin_x86_64.tar.gz"
      sha256 "7954de807829d50d965e43cb718d724018502f5fa970df877f70f47a7d77d3a1"

      def install
        bin.install "refresh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gobuffalo/refresh/releases/download/v1.13.3/refresh_1.13.3_Darwin_arm64.tar.gz"
      sha256 "8a3d456299a1800a9064e11c305945978ae9d082f668f3716539e21357960eb2"

      def install
        bin.install "refresh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gobuffalo/refresh/releases/download/v1.13.3/refresh_1.13.3_Linux_arm64.tar.gz"
      sha256 "f74be53a3599970ade9f2e406e518333dfa12dd23f1102a4055ee1f81c26ef4d"

      def install
        bin.install "refresh"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gobuffalo/refresh/releases/download/v1.13.3/refresh_1.13.3_Linux_armv6.tar.gz"
      sha256 "600402fd860c7cb608c00ce07643f934c47af7ebd41128d926c8533b55da5048"

      def install
        bin.install "refresh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/refresh/releases/download/v1.13.3/refresh_1.13.3_Linux_x86_64.tar.gz"
      sha256 "477c9a86e6df41e93e53f895c385cac4fda6d33fa3bf05225af71b0a59a1393d"

      def install
        bin.install "refresh"
      end
    end
  end
end
