# This file was generated by GoReleaser. DO NOT EDIT.
class Release < Formula
  desc ""
  homepage ""
  version "1.13.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gobuffalo/release/releases/download/v1.13.2/release_1.13.2_darwin_amd64.tar.gz"
    sha256 "be91ddd4f235ebc76000614f3472b1ef98a4a9a6ed85bae6ed99b025bf69e730"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/release/releases/download/v1.13.2/release_1.13.2_linux_amd64.tar.gz"
      sha256 "fca241ce97434e063976a663afbe05d2e0c5b29121aa0d239dac04587e106620"
    end
  end

  def install
    bin.install "release"
  end
end
