# This file was generated by GoReleaser. DO NOT EDIT.
class Release < Formula
  desc ""
  homepage ""
  version "1.12.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gobuffalo/release/releases/download/v1.12.0/release_1.12.0_darwin_amd64.tar.gz"
    sha256 "3152a68ffdb3b5072ede2bbdb78127f885a9a7e1a15aa94dff5903785a5ebfbb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gobuffalo/release/releases/download/v1.12.0/release_1.12.0_linux_amd64.tar.gz"
      sha256 "4234f6505a32a45abe1c2de75b46000ea4b861e3269a6f091fb0469d07eb0371"
    end
  end

  def install
    bin.install "release"
  end
end
